// src/ocr/word-list.ts — Common English words for OCR spell-check validation
//
// This list covers:
//  - Fry sight words (most common 1000 English words)
//  - Common K-8 spelling list vocabulary
//  - Words with tricky patterns (silent letters, digraphs, etc.)
//
// Words are lowercase and sorted alphabetically for maintainability.
// The WORD_SET is built once at module load for O(1) lookups.

const WORDS: readonly string[] = [
  // A
  'a', 'able', 'about', 'above', 'absent', 'accept', 'accident', 'account',
  'ache', 'achieve', 'across', 'act', 'action', 'active', 'activity', 'actual',
  'actually', 'add', 'address', 'admit', 'adult', 'advance', 'adventure',
  'advice', 'afraid', 'after', 'afternoon', 'again', 'against', 'age', 'ago',
  'agree', 'ahead', 'air', 'airplane', 'alive', 'all', 'allow', 'almost',
  'alone', 'along', 'already', 'also', 'always', 'am', 'among', 'amount',
  'an', 'ancient', 'and', 'angel', 'anger', 'angle', 'angry', 'animal',
  'announce', 'another', 'answer', 'ant', 'any', 'anybody', 'anyone',
  'anything', 'anyway', 'apart', 'apartment', 'appear', 'apple', 'apply',
  'approach', 'are', 'area', 'argue', 'arm', 'army', 'around', 'arrange',
  'arrive', 'art', 'article', 'as', 'ask', 'asleep', 'at', 'attack',
  'attempt', 'attend', 'attention', 'aunt', 'author', 'autumn', 'available',
  'average', 'avoid', 'awake', 'award', 'aware', 'away', 'awful',

  // B
  'baby', 'back', 'backward', 'bad', 'badge', 'bag', 'bake', 'balance',
  'ball', 'balloon', 'banana', 'band', 'bank', 'bar', 'bare', 'barn',
  'base', 'basic', 'basket', 'bat', 'bath', 'bathroom', 'battle', 'be',
  'beach', 'bean', 'bear', 'beat', 'beautiful', 'beauty', 'became', 'because',
  'become', 'bed', 'bedroom', 'been', 'before', 'began', 'begin', 'beginning',
  'behave', 'behind', 'believe', 'bell', 'belong', 'below', 'bend', 'beneath',
  'beside', 'besides', 'best', 'better', 'between', 'beyond', 'bicycle',
  'big', 'bike', 'bill', 'bird', 'birth', 'birthday', 'bit', 'bite', 'black',
  'blanket', 'bleed', 'blind', 'block', 'blood', 'blow', 'blue', 'board',
  'boat', 'body', 'bone', 'book', 'boot', 'born', 'borrow', 'boss', 'both',
  'bother', 'bottle', 'bottom', 'bought', 'bounce', 'bow', 'bowl', 'box',
  'boy', 'brain', 'branch', 'brave', 'bread', 'break', 'breakfast', 'breath',
  'breathe', 'brick', 'bridge', 'brief', 'bright', 'bring', 'broad',
  'broke', 'broken', 'brother', 'brought', 'brown', 'brush', 'bubble',
  'build', 'building', 'bump', 'bunch', 'burn', 'burst', 'bury', 'bus',
  'bush', 'business', 'busy', 'but', 'butter', 'button', 'buy', 'by',

  // C
  'cabin', 'cage', 'cake', 'call', 'calm', 'came', 'camera', 'camp', 'can',
  'cancel', 'candle', 'candy', 'cap', 'capable', 'capital', 'captain', 'capture',
  'car', 'card', 'care', 'careful', 'carefully', 'careless', 'carry', 'case',
  'cast', 'castle', 'cat', 'catch', 'caught', 'cause', 'cave', 'celebrate',
  'center', 'central', 'century', 'cereal', 'certain', 'certainly', 'chain',
  'chair', 'challenge', 'champion', 'chance', 'change', 'chapter', 'character',
  'charge', 'charm', 'chase', 'cheap', 'check', 'cheer', 'cheese', 'chest',
  'chicken', 'chief', 'child', 'children', 'chin', 'chip', 'chocolate',
  'choice', 'choose', 'chose', 'chosen', 'church', 'circle', 'circus', 'citizen',
  'city', 'claim', 'clap', 'class', 'classic', 'clean', 'clear', 'clearly',
  'clever', 'cliff', 'climb', 'clock', 'close', 'closet', 'cloth', 'clothes',
  'clothing', 'cloud', 'club', 'clue', 'coach', 'coast', 'coat', 'code',
  'coffee', 'coin', 'cold', 'collect', 'collection', 'college', 'color',
  'column', 'combine', 'come', 'comfort', 'comfortable', 'command', 'comment',
  'common', 'communicate', 'community', 'company', 'compare', 'compete',
  'competition', 'complete', 'completely', 'complex', 'computer', 'concern',
  'condition', 'conference', 'confidence', 'confirm', 'confuse', 'connect',
  'connection', 'consider', 'consist', 'constant', 'construct', 'contact',
  'contain', 'content', 'contest', 'continue', 'control', 'conversation',
  'cook', 'cookie', 'cool', 'copy', 'core', 'corn', 'corner', 'correct',
  'cost', 'cotton', 'could', 'count', 'country', 'couple', 'courage', 'course',
  'court', 'cousin', 'cover', 'cow', 'crack', 'crash', 'crazy', 'cream',
  'create', 'creature', 'crew', 'crime', 'cross', 'crowd', 'cruel', 'crush',
  'cry', 'cup', 'curious', 'current', 'curtain', 'curve', 'custom', 'customer',
  'cut', 'cute', 'cycle',

  // D
  'dad', 'daily', 'damage', 'dance', 'danger', 'dangerous', 'dare', 'dark',
  'darkness', 'data', 'date', 'daughter', 'day', 'dead', 'deal', 'dear',
  'death', 'debate', 'decide', 'decision', 'deck', 'declare', 'deep',
  'deeply', 'deer', 'defeat', 'defend', 'define', 'degree', 'delay',
  'delicate', 'deliver', 'demand', 'department', 'depend', 'depth', 'describe',
  'description', 'desert', 'design', 'desk', 'despite', 'destroy', 'detail',
  'determine', 'develop', 'device', 'diamond', 'did', 'die', 'diet',
  'difference', 'different', 'difficult', 'difficulty', 'dig', 'dinner',
  'direct', 'direction', 'director', 'dirt', 'dirty', 'disappear', 'discover',
  'discovery', 'discuss', 'discussion', 'disease', 'dish', 'display',
  'distance', 'distant', 'divide', 'do', 'doctor', 'does', 'dog', 'dollar',
  'done', 'door', 'dot', 'double', 'doubt', 'down', 'downtown', 'dozen',
  'draft', 'drag', 'dragon', 'drama', 'draw', 'drawing', 'dream', 'dress',
  'drew', 'drink', 'drive', 'drop', 'drove', 'dry', 'duck', 'due', 'dull',
  'during', 'dust', 'duty',

  // E
  'each', 'eager', 'ear', 'early', 'earn', 'earth', 'ease', 'easily', 'east',
  'eastern', 'easy', 'eat', 'edge', 'education', 'effect', 'effort', 'egg',
  'eight', 'either', 'electric', 'electricity', 'element', 'elephant',
  'else', 'emergency', 'emotion', 'employ', 'empty', 'enable', 'encourage',
  'end', 'enemy', 'energy', 'engine', 'engineer', 'enjoy', 'enormous',
  'enough', 'enter', 'entire', 'entirely', 'entrance', 'entry', 'environment',
  'equal', 'equipment', 'error', 'escape', 'especially', 'essay', 'essential',
  'establish', 'even', 'evening', 'event', 'eventually', 'ever', 'every',
  'everybody', 'everyday', 'everyone', 'everything', 'everywhere', 'evidence',
  'evil', 'exact', 'exactly', 'exam', 'examine', 'example', 'excellent',
  'except', 'exchange', 'excite', 'excited', 'excitement', 'exciting',
  'excuse', 'exercise', 'exist', 'exit', 'expect', 'expensive', 'experience',
  'experiment', 'expert', 'explain', 'explanation', 'explore', 'express',
  'expression', 'extend', 'extra', 'extreme', 'extremely', 'eye',

  // F
  'face', 'fact', 'factor', 'factory', 'fail', 'fair', 'fairly', 'faith',
  'fall', 'false', 'familiar', 'family', 'famous', 'fan', 'fancy', 'far',
  'farm', 'farmer', 'fast', 'fat', 'fate', 'father', 'fault', 'favor',
  'favorite', 'fear', 'feast', 'feather', 'feature', 'fed', 'feed', 'feel',
  'feeling', 'feet', 'fell', 'fellow', 'felt', 'female', 'fence', 'festival',
  'fever', 'few', 'field', 'fierce', 'fifteen', 'fifth', 'fifty', 'fight',
  'figure', 'fill', 'film', 'final', 'finally', 'find', 'fine', 'finger',
  'finish', 'fire', 'firm', 'first', 'fish', 'fit', 'five', 'fix', 'flag',
  'flame', 'flash', 'flat', 'flavor', 'flew', 'flight', 'flip', 'float',
  'flood', 'floor', 'flow', 'flower', 'fly', 'focus', 'fold', 'folk',
  'follow', 'food', 'fool', 'foot', 'football', 'for', 'force', 'foreign',
  'forest', 'forever', 'forget', 'forgive', 'fork', 'form', 'formal',
  'former', 'fort', 'forth', 'fortune', 'forward', 'found', 'foundation',
  'four', 'fourth', 'fox', 'frame', 'free', 'freedom', 'freeze', 'french',
  'frequency', 'frequent', 'fresh', 'friend', 'friendly', 'friendship',
  'fright', 'frighten', 'from', 'front', 'frozen', 'fruit', 'fuel', 'full',
  'fully', 'fun', 'function', 'funny', 'fur', 'furniture', 'further', 'future',

  // G
  'gain', 'game', 'gang', 'garage', 'garden', 'gas', 'gate', 'gather', 'gave',
  'gem', 'gems', 'general', 'generally', 'generation', 'generous', 'gentle',
  'gentleman', 'gently', 'genuine', 'get', 'ghost', 'giant', 'gift', 'giraffe',
  'girl', 'give', 'given', 'glad', 'glass', 'global', 'glory', 'glove',
  'glow', 'go', 'goal', 'god', 'gold', 'golden', 'golf', 'gone', 'good',
  'government', 'grab', 'grace', 'grade', 'grain', 'grand', 'grandfather',
  'grandmother', 'grant', 'grass', 'grateful', 'grave', 'gray', 'great',
  'green', 'greet', 'grew', 'grip', 'ground', 'group', 'grow', 'growth',
  'guarantee', 'guard', 'guess', 'guest', 'guide', 'guilty', 'guitar', 'gun',
  'guy',

  // H
  'habit', 'had', 'hair', 'half', 'hall', 'hand', 'handle', 'handsome', 'hang',
  'happen', 'happy', 'harbor', 'hard', 'hardly', 'harm', 'has', 'hat', 'hate',
  'have', 'he', 'head', 'health', 'healthy', 'hear', 'heard', 'heart', 'heat',
  'heaven', 'heavy', 'height', 'held', 'hello', 'help', 'helpful', 'her',
  'here', 'hero', 'herself', 'hide', 'high', 'highly', 'hill', 'him',
  'himself', 'hint', 'hip', 'hire', 'his', 'history', 'hit', 'hold', 'hole',
  'holiday', 'hollow', 'home', 'honest', 'honor', 'hook', 'hope', 'horizon',
  'horrible', 'horror', 'horse', 'hospital', 'host', 'hot', 'hotel', 'hour',
  'house', 'household', 'how', 'however', 'huge', 'human', 'humor', 'hundred',
  'hungry', 'hunt', 'hurry', 'hurt', 'husband',

  // I
  'i', 'ice', 'idea', 'identify', 'if', 'ignore', 'ill', 'illegal', 'image',
  'imagine', 'immediate', 'immediately', 'impact', 'imply', 'import',
  'important', 'impose', 'impossible', 'impress', 'impression', 'improve',
  'in', 'inch', 'incident', 'include', 'income', 'increase', 'indeed',
  'independent', 'indicate', 'individual', 'industry', 'influence',
  'information', 'initial', 'injury', 'inner', 'innocent', 'insect', 'inside',
  'insist', 'inspire', 'install', 'instance', 'instead', 'institution',
  'instruction', 'instrument', 'insurance', 'intelligence', 'intend',
  'intense', 'interest', 'interesting', 'internal', 'international',
  'internet', 'interview', 'into', 'introduce', 'introduction', 'invade',
  'invest', 'investigate', 'investigation', 'investment', 'invite', 'involve',
  'iron', 'island', 'issue', 'it', 'item', 'its', 'itself',

  // J
  'jacket', 'jail', 'jam', 'jar', 'jaw', 'jealous', 'jet', 'jewel', 'jewelry',
  'job', 'join', 'joke', 'journal', 'journey', 'joy', 'judge', 'juice', 'jump',
  'jungle', 'junior', 'jury', 'just', 'justice',

  // K
  'keen', 'keep', 'kept', 'key', 'kick', 'kid', 'kill', 'kind', 'king',
  'kingdom', 'kiss', 'kit', 'kitchen', 'knee', 'knew', 'knife', 'knight',
  'knock', 'knot', 'know', 'knowledge', 'known',

  // L
  'lab', 'label', 'labor', 'lack', 'ladder', 'lady', 'laid', 'lake', 'lamp',
  'land', 'landscape', 'language', 'lap', 'large', 'largely', 'last', 'late',
  'later', 'latest', 'latter', 'laugh', 'launch', 'law', 'lawn', 'lawyer',
  'lay', 'layer', 'lazy', 'lead', 'leader', 'leadership', 'leaf', 'league',
  'lean', 'learn', 'learning', 'least', 'leather', 'leave', 'led', 'left',
  'leg', 'legal', 'legend', 'lemon', 'length', 'lesson', 'let', 'letter',
  'level', 'library', 'license', 'lie', 'life', 'lift', 'light', 'like',
  'likely', 'limit', 'line', 'link', 'lion', 'lip', 'list', 'listen',
  'literature', 'little', 'live', 'living', 'load', 'loan', 'local', 'locate',
  'location', 'lock', 'log', 'lonely', 'long', 'look', 'loose', 'lord',
  'lose', 'loss', 'lost', 'lot', 'loud', 'love', 'lovely', 'low', 'lower',
  'luck', 'lucky', 'lunch',

  // M
  'machine', 'mad', 'magazine', 'magic', 'mail', 'main', 'mainly', 'maintain',
  'major', 'majority', 'make', 'male', 'mall', 'man', 'manage', 'manager',
  'manner', 'many', 'map', 'march', 'mark', 'market', 'marriage', 'married',
  'marry', 'mask', 'mass', 'master', 'match', 'mate', 'material', 'math',
  'matter', 'may', 'maybe', 'mayor', 'me', 'meal', 'mean', 'meaning',
  'measure', 'meat', 'media', 'medical', 'medicine', 'medium', 'meet',
  'meeting', 'member', 'membership', 'memory', 'mental', 'mention', 'menu',
  'merchant', 'mercy', 'merely', 'mess', 'message', 'metal', 'method',
  'mice', 'middle', 'might', 'mile', 'military', 'milk', 'million', 'mind',
  'mine', 'minute', 'mirror', 'miss', 'mission', 'mistake', 'mix', 'mixture',
  'model', 'modern', 'mom', 'moment', 'money', 'monitor', 'monkey', 'month',
  'mood', 'moon', 'moral', 'more', 'morning', 'most', 'mostly', 'mother',
  'motion', 'motor', 'mountain', 'mouse', 'mouth', 'move', 'movement',
  'movie', 'much', 'mud', 'multiple', 'murder', 'muscle', 'museum', 'music',
  'musical', 'must', 'my', 'myself', 'mystery',

  // N
  'nail', 'name', 'narrow', 'nation', 'national', 'natural', 'naturally',
  'nature', 'near', 'nearby', 'nearly', 'neat', 'necessary', 'neck', 'need',
  'negative', 'neighbor', 'neighborhood', 'neither', 'nerve', 'nervous',
  'nest', 'net', 'network', 'never', 'new', 'news', 'newspaper', 'next',
  'nice', 'night', 'nine', 'no', 'nobody', 'nod', 'noise', 'none', 'nor',
  'normal', 'normally', 'north', 'northern', 'nose', 'not', 'note', 'nothing',
  'notice', 'noun', 'novel', 'now', 'nowhere', 'number', 'nurse', 'nut',

  // O
  'object', 'observe', 'obtain', 'obvious', 'obviously', 'occasion',
  'occur', 'ocean', 'odd', 'of', 'off', 'offer', 'office', 'officer',
  'official', 'often', 'oil', 'ok', 'old', 'on', 'once', 'one', 'online',
  'only', 'onto', 'open', 'opening', 'operate', 'operation', 'opinion',
  'opponent', 'opportunity', 'oppose', 'opposite', 'option', 'or', 'orange',
  'order', 'ordinary', 'organize', 'original', 'other', 'otherwise', 'ought',
  'our', 'ourselves', 'out', 'outcome', 'outside', 'over', 'overall',
  'overcome', 'owe', 'own', 'owner',

  // P
  'pace', 'pack', 'package', 'pad', 'page', 'paid', 'pain', 'paint', 'pair',
  'palace', 'pale', 'palm', 'pan', 'panel', 'panic', 'paper', 'paragraph',
  'parent', 'park', 'parking', 'part', 'particular', 'particularly', 'partly',
  'partner', 'party', 'pass', 'passage', 'passenger', 'passion', 'past',
  'path', 'patience', 'patient', 'pattern', 'pause', 'pay', 'payment',
  'peace', 'peaceful', 'peak', 'pen', 'penalty', 'pencil', 'penny', 'people',
  'pepper', 'per', 'percent', 'perfect', 'perfectly', 'perform', 'performance',
  'perhaps', 'period', 'permanent', 'permission', 'permit', 'person',
  'personal', 'personality', 'perspective', 'pet', 'phase', 'phone',
  'photo', 'photograph', 'phrase', 'physical', 'piano', 'pick', 'picture',
  'pie', 'piece', 'pig', 'pile', 'pilot', 'pin', 'pink', 'pipe', 'pitch',
  'place', 'plain', 'plan', 'plane', 'planet', 'plant', 'plate', 'platform',
  'play', 'player', 'pleasant', 'please', 'pleasure', 'plenty', 'plus',
  'pocket', 'poem', 'poet', 'poetry', 'point', 'poison', 'pole', 'police',
  'policy', 'polite', 'political', 'politics', 'pollution', 'pond', 'pool',
  'poor', 'pop', 'popular', 'population', 'porch', 'port', 'portion',
  'position', 'positive', 'possess', 'possession', 'possibility', 'possible',
  'possibly', 'post', 'pot', 'potato', 'potential', 'pound', 'pour', 'poverty',
  'power', 'powerful', 'practice', 'pray', 'prayer', 'predict', 'prefer',
  'prepare', 'presence', 'present', 'president', 'press', 'pressure',
  'pretend', 'pretty', 'prevent', 'previous', 'price', 'pride', 'priest',
  'primary', 'prince', 'princess', 'principal', 'principle', 'print', 'prior',
  'prison', 'prisoner', 'privacy', 'private', 'prize', 'probably', 'problem',
  'procedure', 'proceed', 'process', 'produce', 'product', 'production',
  'profession', 'professional', 'professor', 'profit', 'program', 'progress',
  'project', 'promise', 'promote', 'proof', 'proper', 'properly', 'property',
  'proposal', 'propose', 'protect', 'protection', 'protest', 'proud', 'prove',
  'provide', 'public', 'pull', 'punch', 'punishment', 'pupil', 'purchase',
  'pure', 'purple', 'purpose', 'pursue', 'push', 'put', 'puzzle',

  // Q
  'qualify', 'quality', 'quarter', 'queen', 'question', 'quick', 'quickly',
  'quiet', 'quietly', 'quit', 'quite', 'quote',

  // R
  'race', 'radio', 'rage', 'rail', 'rain', 'raise', 'range', 'rank', 'rapid',
  'rare', 'rarely', 'rat', 'rate', 'rather', 'raw', 'reach', 'react',
  'reaction', 'read', 'reader', 'reading', 'ready', 'real', 'reality',
  'realize', 'really', 'reason', 'reasonable', 'receive', 'recent', 'recently',
  'recognize', 'recommend', 'record', 'recover', 'red', 'reduce', 'refer',
  'reflect', 'reform', 'refuse', 'regard', 'region', 'register', 'regular',
  'reject', 'relate', 'relation', 'relationship', 'relative', 'relax',
  'release', 'relief', 'religion', 'religious', 'rely', 'remain', 'remaining',
  'remark', 'remember', 'remind', 'remote', 'remove', 'rent', 'repair',
  'repeat', 'replace', 'reply', 'report', 'represent', 'require', 'research',
  'resident', 'resist', 'resolve', 'resource', 'respect', 'respond',
  'response', 'responsible', 'rest', 'restaurant', 'restore', 'result',
  'retire', 'return', 'reveal', 'review', 'revolution', 'reward', 'rhythm',
  'rice', 'rich', 'rid', 'ride', 'right', 'ring', 'rise', 'risk', 'river',
  'road', 'robot', 'rock', 'role', 'roll', 'roof', 'room', 'root', 'rope',
  'rose', 'rough', 'round', 'route', 'row', 'royal', 'rub', 'rude', 'ruin',
  'rule', 'run', 'runner', 'rural', 'rush',

  // S
  'sacred', 'sad', 'safe', 'safety', 'said', 'sail', 'sake', 'salad', 'salary',
  'sale', 'salt', 'same', 'sample', 'sand', 'sandwich', 'sat', 'satisfy',
  'save', 'saw', 'say', 'scale', 'scene', 'schedule', 'scholar', 'school',
  'science', 'scientist', 'score', 'screen', 'sea', 'search', 'season',
  'seat', 'second', 'secret', 'section', 'secure', 'security', 'see', 'seed',
  'seek', 'seem', 'seen', 'seize', 'select', 'selection', 'self', 'sell',
  'send', 'senior', 'sense', 'sentence', 'separate', 'sequence', 'series',
  'serious', 'seriously', 'serve', 'service', 'session', 'set', 'settle',
  'settlement', 'seven', 'several', 'severe', 'shadow', 'shake', 'shall',
  'shame', 'shape', 'share', 'sharp', 'she', 'sheep', 'sheet', 'shelf',
  'shell', 'shelter', 'shift', 'shine', 'ship', 'shirt', 'shock', 'shoe',
  'shoot', 'shop', 'shopping', 'shore', 'short', 'shortly', 'shot', 'should',
  'shoulder', 'shout', 'show', 'shower', 'shut', 'shy', 'sick', 'side',
  'sight', 'sign', 'signal', 'silence', 'silent', 'silly', 'silver', 'similar',
  'simple', 'simply', 'since', 'sing', 'singer', 'single', 'sir', 'sister',
  'sit', 'site', 'situation', 'six', 'size', 'skill', 'skin', 'sky', 'slave',
  'sleep', 'slice', 'slide', 'slight', 'slightly', 'slip', 'slow', 'slowly',
  'small', 'smart', 'smell', 'smile', 'smoke', 'smooth', 'snake', 'snow',
  'so', 'soap', 'social', 'society', 'soft', 'software', 'soil', 'solar',
  'soldier', 'solid', 'solution', 'solve', 'some', 'somebody', 'someday',
  'somehow', 'someone', 'something', 'sometimes', 'somewhat', 'somewhere',
  'son', 'song', 'soon', 'sorry', 'sort', 'soul', 'sound', 'soup', 'source',
  'south', 'southern', 'space', 'speak', 'speaker', 'special', 'specific',
  'specifically', 'speech', 'speed', 'spell', 'spelling', 'spend', 'spent',
  'spider', 'spirit', 'split', 'spoke', 'sport', 'spot', 'spread', 'spring',
  'square', 'stable', 'staff', 'stage', 'stair', 'stake', 'stand', 'standard',
  'star', 'stare', 'start', 'state', 'statement', 'station', 'status', 'stay',
  'steady', 'steal', 'steam', 'steel', 'steep', 'step', 'stick', 'stiff',
  'still', 'stock', 'stomach', 'stone', 'stood', 'stop', 'store', 'storm',
  'story', 'straight', 'strange', 'stranger', 'strategy', 'stream', 'street',
  'strength', 'stress', 'stretch', 'strict', 'strike', 'string', 'strip',
  'stroke', 'strong', 'strongly', 'structure', 'struggle', 'student', 'study',
  'stuff', 'stupid', 'style', 'subject', 'submit', 'succeed', 'success',
  'successful', 'such', 'sudden', 'suddenly', 'suffer', 'sufficient', 'sugar',
  'suggest', 'suit', 'summer', 'sun', 'super', 'supply', 'support', 'suppose',
  'sure', 'surely', 'surface', 'surprise', 'surround', 'survey', 'survive',
  'suspect', 'sweet', 'swim', 'swing', 'switch', 'symbol', 'system',

  // T
  'table', 'tail', 'take', 'tale', 'talent', 'talk', 'tall', 'tank', 'tap',
  'tape', 'target', 'task', 'taste', 'taught', 'tax', 'tea', 'teach',
  'teacher', 'teaching', 'team', 'tear', 'technology', 'telephone',
  'television', 'tell', 'temperature', 'ten', 'tend', 'tension', 'term',
  'terms', 'terrible', 'test', 'text', 'than', 'thank', 'thanks', 'that',
  'the', 'theater', 'their', 'them', 'theme', 'themselves', 'then', 'theory',
  'therapy', 'there', 'therefore', 'these', 'they', 'thick', 'thin', 'thing',
  'think', 'third', 'thirty', 'this', 'those', 'though', 'thought', 'thousand',
  'threat', 'threaten', 'three', 'throat', 'through', 'throughout', 'throw',
  'thus', 'ticket', 'tide', 'tie', 'tight', 'till', 'time', 'tiny', 'tip',
  'tire', 'tired', 'title', 'to', 'today', 'toe', 'together', 'tomorrow',
  'tone', 'tongue', 'tonight', 'too', 'tool', 'tooth', 'top', 'topic',
  'total', 'totally', 'touch', 'tough', 'tour', 'tourist', 'toward',
  'towards', 'tower', 'town', 'toy', 'trace', 'track', 'trade', 'tradition',
  'traditional', 'traffic', 'trail', 'train', 'training', 'transfer',
  'transform', 'transportation', 'travel', 'treat', 'treatment', 'tree',
  'tremendous', 'trend', 'trial', 'tribe', 'trick', 'trip', 'troop',
  'trouble', 'truck', 'true', 'truly', 'trust', 'truth', 'try', 'tube',
  'tunnel', 'turn', 'twelve', 'twenty', 'twice', 'twin', 'twist', 'two',
  'type', 'typical', 'typically',

  // U
  'ugly', 'ultimate', 'unable', 'uncle', 'under', 'understand', 'union',
  'unique', 'unit', 'united', 'universe', 'university', 'unknown', 'unless',
  'unlike', 'unlikely', 'until', 'unusual', 'up', 'upon', 'upper', 'upset',
  'urban', 'urge', 'us', 'use', 'used', 'useful', 'user', 'usual', 'usually',

  // V
  'vacation', 'valley', 'valuable', 'value', 'variety', 'various', 'vast',
  'vegetable', 'vehicle', 'venture', 'version', 'very', 'veteran', 'victory',
  'video', 'view', 'village', 'violence', 'violent', 'virtual', 'virtue',
  'vision', 'visit', 'visitor', 'vital', 'vocabulary', 'voice', 'volume',
  'volunteer', 'vote', 'vulnerable',

  // W
  'wage', 'wait', 'wake', 'walk', 'wall', 'want', 'war', 'warm', 'warn',
  'warning', 'wash', 'waste', 'watch', 'water', 'wave', 'way', 'we', 'weak',
  'weakness', 'wealth', 'weapon', 'wear', 'weather', 'web', 'website',
  'wedding', 'week', 'weekend', 'weigh', 'weight', 'welcome', 'well', 'went',
  'were', 'west', 'western', 'wet', 'what', 'whatever', 'wheat', 'wheel',
  'when', 'whenever', 'where', 'whereas', 'wherever', 'whether', 'which',
  'while', 'whisper', 'white', 'who', 'whoever', 'whole', 'whom', 'whose',
  'why', 'wide', 'widely', 'wife', 'wild', 'will', 'willing', 'win', 'wind',
  'window', 'wine', 'wing', 'winner', 'winter', 'wire', 'wisdom', 'wise',
  'wish', 'with', 'withdraw', 'within', 'without', 'witness', 'woman',
  'women', 'wonder', 'wonderful', 'wood', 'wooden', 'wool', 'word', 'words',
  'work', 'worker', 'working', 'world', 'worried', 'worry', 'worse', 'worst',
  'worth', 'would', 'wound', 'wrap', 'write', 'writer', 'writing', 'written',
  'wrong', 'wrote',

  // Y
  'yard', 'yeah', 'year', 'yell', 'yellow', 'yes', 'yesterday', 'yet', 'you',
  'young', 'youngster', 'your', 'yours', 'yourself', 'youth',

  // Z
  'zero', 'zone', 'zoo',
];

/** O(1) lookup set built once at module load. */
export const WORD_SET: ReadonlySet<string> = new Set(WORDS);
